### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by asifiqbal** [thbe/puppet-openscap#1]
com.redhat.rhsa-all.xml.bz2

I downloaded it from www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2 to fix it

**Comment by thbe** [comment]
See NOTICE (https://github.com/thbe/puppet-openscap/blob/master/files/NOTICE) in files directory. This file needs regular upgrades and is therefor not distributed within the module ... and because it is quite big ...
