### ISSUE TITLE
facter lsbmajdistrelease is not found

### ISSUE THREAD

**Issue by asifiqbal** [thbe/puppet-openscap#2]
I am using puppet 3.8.7 on centos 6.5. I changed it to operatingsystemmajrelease on package.pp and now it does not fail to install anymore.

Thanks a lot for a nice module.

**Comment by thbe** [comment]
Feel free to create a pull request to get this changes incorporated in this module. I've restricted the releases to the one I use regularly so I can better see if something goes wrong, I'm pretty sure it work with other releases as well ...
